import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


const didot = localFont({
  src: [
    {
      path: './fonts/didot/Didot Bold Italic.ttf',
      weight: '400',
      style: 'bold_italic',
      variable: "--font-didot-bold-italic",

    },
    {
      path: './fonts/didot/Didot Medium.ttf',
      weight: '200',
      style: 'medium',
      variable: "--font-didot-medium",
    },
    {
      path: './fonts/didot/Didot Regular.ttf',
      weight: '400',
      style: 'regular',
      variable: "--font-didot-regular",

    },
  ],
})

export const metadata = {
  title: "French - Home Goods Concept Store - Specializing In French Imports- French.US ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
